/*
* Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
*/
#pragma once

#define FILTER_DEGEN_UV_TRIS_BINDING_DST_INDICES         1180
#define FILTER_DEGEN_UV_TRIS_BINDING_SRC_INDICES_U16     1181
#define FILTER_DEGEN_UV_TRIS_BINDING_SRC_INDICES_U32     1182
#define FILTER_DEGEN_UV_TRIS_BINDING_INTERLEAVED_VERTS   1183
